### ISSUE TITLE
This files crashes almost instantly on every frame change

### ISSUE THREAD

**Issue by YorsLosilla** [JacquesLucke/animation_nodes#256] opened 2015-10-10 18:27 UTC
It´s the final animation for the reel thing. Maybe I´m pushing the addon to its limits or it´s any blender issue. However I can´t render. Maybe someone has an idea on what could be.

https://drive.google.com/file/d/0B9SDRZRP7NzVdFpMdFlBbk56TDA/view?usp=sharing

I have tried with the last master, few minutes ago and a version that I downloaded a three or four days before. I´m all cases crashes.

Thanks for your attention.

**Comment by YorsLosilla** [comment] 2015-10-10 18:33
I have also tried with the 2.74 Fracture Modfier Build. It crashes on the same way. So maybe it´s AN issue.

**Comment by YorsLosilla** [comment] 2015-10-10 19:45
This is the message I get when I click the Retry button on the AN Tools Panel

Traceback (most recent call last):
  File "/Users/yorsdelajungla/Library/Application Support/Blender/2.76/scripts/addons/animation_nodes-master/execution/main_execution_unit.py", line 39, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'Poligonos'", line 28, in <module>
  File "group: 'Loop'", line 101, in main
  File "/Users/yorsdelajungla/Library/Application Support/Blender/2.76/scripts/addons/animation_nodes-master/utils/math.py", line 5, in composeMatrix
    matrix *= Euler(rotation).to_matrix().to_4x4()
ValueError: mathutils.Euler(): sequence size is 2, expected 3






Traceback (most recent call last):
  File "/Users/yorsdelajungla/Library/Application Support/Blender/2.76/scripts/addons/animation_nodes-master/execution/main_execution_unit.py", line 39, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'Poligonos'", line 32, in <module>
  File "group: 'Loop'", line 101, in main
  File "/Users/yorsdelajungla/Library/Application Support/Blender/2.76/scripts/addons/animation_nodes-master/utils/math.py", line 5, in composeMatrix
    matrix *= Euler(rotation).to_matrix().to_4x4()
ValueError: mathutils.Euler(): sequence size is 2, expected 3
dadSASDATime: 0.00362 - fps : 276.01 - Function: update
Time: 0.03030 - fps : 33.01 - Function: updateEverything






Traceback (most recent call last):
  File "/Users/yorsdelajungla/Library/Application Support/Blender/2.76/scripts/addons/animation_nodes-master/execution/main_execution_unit.py", line 39, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'Letras'", line 38, in <module>
  File "group: 'My Loop'", line 44, in main
AttributeError: 'Euler' object has no attribute 'xyz'






Traceback (most recent call last):
  File "/Users/yorsdelajungla/Library/Application Support/Blender/2.76/scripts/addons/animation_nodes-master/execution/main_execution_unit.py", line 39, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'Poligonos'", line 28, in <module>
  File "group: 'Loop'", line 101, in main
  File "/Users/yorsdelajungla/Library/Application Support/Blender/2.76/scripts/addons/animation_nodes-master/utils/math.py", line 5, in composeMatrix
    matrix *= Euler(rotation).to_matrix().to_4x4()
ValueError: mathutils.Euler(): sequence size is 2, expected 3

Traceback (most recent call last):
  File "/Users/yorsdelajungla/Library/Application Support/Blender/2.76/scripts/addons/animation_nodes-master/execution/main_execution_unit.py", line 39, in executeUnit
    exec(self.executeCodeObject, self.executionData, self.executionData)
  File "execution: 'Poligonos'", line 32, in <module>
  File "group: 'Loop'", line 101, in main
  File "/Users/yorsdelajungla/Library/Application Support/Blender/2.76/scripts/addons/animation_nodes-master/utils/math.py", line 5, in composeMatrix
    matrix *= Euler(rotation).to_matrix().to_4x4()
ValueError: mathutils.Euler(): sequence size is 2, expected 3


It´s seem to be someting related to new new euler things.

**Comment by JacquesLucke** [comment] 2015-10-10 21:04
You are right. I will try to fix that tommorow. Thanks for the report

**Comment by JacquesLucke** [comment] 2015-10-12 16:30
Looks like you found multiple errors at the same time :D

1. Recreate the ID Key nodes. The problem here is that the Rotation output is an Euler now and not Vector as before.
![id key uses euler](https://cloud.githubusercontent.com/assets/5881326/10432894/7e9dacbc-710e-11e5-9716-8d2ba0f75ecb.PNG)

2. Replace the direction to rotation and compose matrix node. They also use Euler rotation now

I could not find out yet why blender crashed but I will further investigate this

**Comment by YorsLosilla** [comment] 2015-10-12 16:46
I understand. But how can I replace those node. Should I use Euler to Vector conversions? I will like to meet the deadline for tomorrow.  

-----Mensaje original-----
De: "Jacques Lucke" <notifications@github.com>
Enviado: ‎12/‎10/‎2015 18:30
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] This files crashes almost instantly on everyframe change (#256)

Looks like you found multiple errors at the same time :D
Recreate the ID Key nodes. The problem here is that the Rotation output is an Euler now and not Vector as before.

Replace the direction to rotation and compose matrix node. They also use Euler rotation now
I could not find out yet why blender crashed but I will further investigate this

**Comment by YorsLosilla** [comment] 2015-10-12 16:59
This is even more intriguing when I delete all node trees and hit play animation Blender crashes also. This goes far beyond AN, I will raise a bug report.

**Comment by JacquesLucke** [comment] 2015-10-12 17:30
Another thing you have to do is to recreate the "Shade Object Smooth" nodes (when you use the master version from today)
Yes maybe you have to use the euler to vector node, and the vector to euler node before setting the rotation value on the object.
Its always not very good to change the Animation Nodes version within a single project. Maybe it is even easier for you to download an older version of the nodes. Maybe one that is a few days old, before I implemented all the euler stuff.
Sorry for the circumstances......

Yeah I found that too... I'm still trying to pinpoint the actual problem..

**Comment by YorsLosilla** [comment] 2015-10-12 17:54
Which day did you implemented the Euler thing?


-----Mensaje original-----
De: "Jacques Lucke" <notifications@github.com>
Enviado: ‎12/‎10/‎2015 19:30
Para: "JacquesLucke/animation_nodes" <animation_nodes@noreply.github.com>
CC: "YorsLosilla" <thexchanger@gmail.com>
Asunto: Re: [animation_nodes] This files crashes almost instantly on everyframe change (#256)

Another thing you have to do is to recreate the "Shade Object Smooth" nodes (when you use the master version from today)
Yes maybe you have to use the euler to vector node, and the vector to euler node before setting the rotation value on the object.
Its always not very good to change the Animation Nodes version within a single project. Maybe it is even easier for you to download an older version of the nodes. Maybe one that is a few days old, before I implemented all the euler stuff.
Sorry for the circumstances......
Yeah I found that too... I'm still trying to pinpoint the actual problem..

**Comment by JacquesLucke** [comment] 2015-10-12 17:58
try that: https://github.com/JacquesLucke/animation_nodes/tree/792e5a0ff4469866e5e3a337a787fc24a07eddee

Unfortunally there is still the problem with blender crashing on each frame change....
blender says you have a dependy cycles somewhere in the scene, maybe this has something to do with it... I don't know

**Comment by JacquesLucke** [comment] 2015-10-17 08:52
Seams like the problem is Blender itself here... So I will close this issue

**Closed by JacquesLucke** 2015-10-17 08:52 UTC
