### ISSUE TITLE
Proper socket is missing for a new input to Expression node

### ISSUE THREAD

**Issue by eighty8serge** [JacquesLucke/animation_nodes#1942] opened 2024-01-27 19:08 UTC
Blender 4.0.3 with latest AN
![1](https://github.com/JacquesLucke/animation_nodes/assets/151669582/7f7fcae4-b725-4caf-b1f0-854db9a5f03c)

**Comment by OmarEmaraDev** [comment] 2024-01-28 09:02
I can't reproduce that. Can you check if there are any errors in the console? Can you also try the latest Blender daily build?

**Comment by eighty8serge** [comment] 2024-01-28 11:22
Thanks for your help!

Seems like the problem was due to the file has nodetree created in AN+Extra Nodes. And after opening project in vanilla AN, some nodes appeared as undefined. I thought deleting them will restore functionality, but that not happened.
So to fix this, I had to modify original file in Blener with AN+Extra Nodes, then import back to vanilla.

Here is the error log:```

Traceback (most recent call last):
  File "E:\blender-4.0.3-candidate+v40.f753cf14fca2-windows.amd64\4.0\scripts\addons\animation_nodes\utils\handlers.py", line 65, in loadPost
    handler()
  File "E:\blender-4.0.3-candidate+v40.f753cf14fca2-windows.amd64\4.0\scripts\addons\animation_nodes\events.py", line 71, in fileLoaded
    updateFile()
  File "E:\blender-4.0.3-candidate+v40.f753cf14fca2-windows.amd64\4.0\scripts\addons\animation_nodes\utils\timing.py", line 13, in wrapper
    output = function(*args, **kwargs)
  File "E:\blender-4.0.3-candidate+v40.f753cf14fca2-windows.amd64\4.0\scripts\addons\animation_nodes\base_types\update_file.py", line 13, in updateFile
    tree_info.updateIfNecessary()
  File "E:\blender-4.0.3-candidate+v40.f753cf14fca2-windows.amd64\4.0\scripts\addons\animation_nodes\tree_info\__init__.py", line 33, in updateIfNecessary
    update()
  File "E:\blender-4.0.3-candidate+v40.f753cf14fca2-windows.amd64\4.0\scripts\addons\animation_nodes\utils\timing.py", line 13, in wrapper
    output = function(*args, **kwargs)
  File "E:\blender-4.0.3-candidate+v40.f753cf14fca2-windows.amd64\4.0\scripts\addons\animation_nodes\tree_info\__init__.py", line 22, in update
    _forestData.update()
  File "E:\blender-4.0.3-candidate+v40.f753cf14fca2-windows.amd64\4.0\scripts\addons\animation_nodes\tree_info\forest_data.py", line 26, in update
    self.insertNodeTrees()
  File "E:\blender-4.0.3-candidate+v40.f753cf14fca2-windows.amd64\4.0\scripts\addons\animation_nodes\tree_info\forest_data.py", line 32, in insertNodeTrees
    self.insertNodes(tree.nodes, tree.name)
  File "E:\blender-4.0.3-candidate+v40.f753cf14fca2-windows.amd64\4.0\scripts\addons\animation_nodes\tree_info\forest_data.py", line 70, in insertNodes
    dataTypeBySocket[socketID] = socket.dataType
AttributeError: 'NodeSocket' object has no attribute 'dataType'
```

**Comment by OmarEmaraDev** [comment] 2024-01-28 12:04
When a node tree stops working even after deleting the offending node, there should be big button called "Retry" in the Problems panel that should hopefully resolve any errors.

But it seem this is not an issue with AN itself, so closing.

**Closed by OmarEmaraDev** 2024-01-28 12:04 UTC
