### ISSUE TITLE
Operation visibility missing update

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#387] opened 2016-02-18 05:41 UTC
After toggling on operation visibilities like "Name", "Move", "Remove", it only works with existing item, not update to new inputs until toggling them off and on again. Not sure if it is expected.

![missing_update](https://cloud.githubusercontent.com/assets/494788/13134776/3524d708-d645-11e5-8950-befc799ff0a4.png)

**Comment by JacquesLucke** [comment] 2016-02-19 15:13
yeah I know that it is that way atm... will see how to fix that nicely.
The problem is that these settings are stored per socket and a new socket doesn't (or shouldn't) know about the other sockets. But I'm sure this is solvable :)

**Comment by LeonCheung** [comment] 2016-02-19 15:27
I see.  Another idea just sliip into my mind:

For List nodes, I wonder if it is cool to add a new option that allows to only take visible items into account and ignore the rest.

**Comment by JacquesLucke** [comment] 2016-03-05 19:27
I fixed this for the Combine and Create List nodes. Are there other nodes that need a similiar fix?

**Comment by JacquesLucke** [comment] 2016-03-06 12:44
I'll close this issue. If you find a node with a similiar problem please create a new issue.

**Closed by JacquesLucke** 2016-03-06 12:44 UTC
