### ISSUE TITLE
Bad Performance of certain nodes due to many group nodes

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [JacquesLucke/animation_nodes#1783] opened 2021-09-03 14:42 UTC
Original Post: https://github.com/3DSinghVFX/animation_nodes/issues/175
A sample file is provided.
[BAD PERFORMANCE TEST.zip](https://github.com/JacquesLucke/animation_nodes/files/7106615/BAD.PERFORMANCE.TEST.zip)

It's common for user to make group nodes / loop nodes as presets.
Normally these nodes won't impact the performance at all.
Nevertheless I find viewport fps being extremely low in certain nodes, such as "**Simulation Nodes**" in Extra Nodes by @3DSinghVFX , and "**Disk Cache Nodes**" in Blue-Fox Extension by @harisreedhar.

Just add the node into the node tree, without connecting it to anything or doing anything, will cause significant fps drop for unknown reason. Knowing that as soon as the group nodes are being deleted, fps will come back to normal without any issues.
![image](https://user-images.githubusercontent.com/55994236/132022183-6066aaad-5e85-4761-a65a-96b363e7bb2a.png)
![image](https://user-images.githubusercontent.com/55994236/132022131-3093a498-7003-4392-a32c-ab1566cf18d0.png)

**Comment by OmarEmaraDev** [comment] 2021-11-29 20:57
Can you still replicate this issue?

**Comment by Gerstmann-Bradley** [comment] 2021-11-29 21:02
Yes on 3.0 beta and the newest AN+EN.

**Comment by OmarEmaraDev** [comment] 2021-11-30 20:56
@Gerstmann-Bradley  Can you test #1808?

**Comment by Gerstmann-Bradley** [comment] 2021-12-02 12:10
Sorry to respond late, I was busy these days.
The issue can only be proven to be resolved using either Extra Nodes or Bluefox Extension.
In this case since our artifact doesn't contain Extra Nodes, I can only check it with bluefox's disc cache node in his extension.
the short answer is our artifact seemingly **doesn't improve** anything.

Note, I was testing an experimental version he provided to me long time ago. his code maybe improved afterwards, but I don't think this issue will be on his side unless being proven otherwise.

**Comment by OmarEmaraDev** [comment] 2021-12-04 08:26
@Gerstmann-Bradley At least by looking at the disk cache node by @harisreedhar, the problem is that some class properties are updated inside the execution function and at the same time use `AnimationNode.refresh` as an update function. That means that every single execution will trigger Animation Nodes to recompute every internal structure it have. So execution have a very large overhead.

We could improve internal recomputations in Animation Nodes as I said, but I would attribute this issue to the extension and should ideally be fixed downstream.

**Comment by harisreedhar** [comment] 2021-12-04 09:21
@OmarEmaraDev Thanks for pointing me about the overhead. I'll look into that

**Comment by Gerstmann-Bradley** [comment] 2021-12-04 10:21
I see. I'm not sure how this new fix will impact simulation node in extra nodes. At least this is what really matters for me about this issue. I guess we can commit this fix and see how things are finally improved in AN+EN? @3DSinghVFX

**Comment by OmarEmaraDev** [comment] 2021-12-19 13:23
Fixed in 27a3c66.

**Closed by OmarEmaraDev** 2021-12-19 13:23 UTC
Labels: pending
