### ISSUE TITLE
The Scripts Node crashes Blender

### ISSUE THREAD

**Issue by ogierm** [JacquesLucke/animation_nodes#1013] opened 2019-01-21 18:17 UTC
1. Add a scripts node and an input to it. 
2. Then connect something to it.
3. Watch Blender go

**Comment by OmarSquircleArt** [comment] 2019-01-22 16:17
Looks like a bug in `window_manager.popup_menu`, I can't reproduce it with a simple script, so I not sure if it can be reported as is.

**Comment by OgierM** [comment] 2019-01-23 09:33
Hmm, I haven't even added a script.

**Comment by OmarSquircleArt** [comment] 2019-01-23 13:00
It should work fine if you don't attempt to connect something to the input and output sockets. You really shouldn't be doing that anyway. The bug happens when Animation Nodes tries to tell you that you shouldn't do that, and instead, use an invoke node.

**Comment by OgierM** [comment] 2019-01-24 00:38
Oh, haha, TIL. I always assumed it worked similar to the Expression node.
Anyways - Do you know if compiling AN yourself or using Linux improves stability?

**Comment by OmarSquircleArt** [comment] 2019-01-24 08:52
Compiling AN yourself make sure you are always up to date and that your builds are compatible with your system. So if you can, start compiling. As for linux, it depends on what distribution you use, some of them are more stable that others. Some things will break and you have to be prepared to fix them. But generally, benchmarks show that linux have better performance than windows.

**Comment by OmarSquircleArt** [comment] 2019-03-02 15:07
Related:
https://developer.blender.org/T62074#anchor-631029

**Comment by ilayshp** [comment] 2019-09-02 11:49
Hello. I'm with such report. 
I add Script node, add Object List input port and try to connect with Object output in Collection Info node.
[blender_debug_output.txt](https://github.com/JacquesLucke/animation_nodes/files/3565907/blender_debug_output.txt)
[script_crash.zip](https://github.com/JacquesLucke/animation_nodes/files/3565911/script_crash.zip)

**Comment by OmarEmaraDev** [comment] 2019-10-03 21:12
Fixed in b02e049.

**Closed by OmarEmaraDev** 2019-10-03 21:12 UTC
Labels: 2.8
