### ISSUE TITLE
Frame Rate Drop with Single Node

### ISSUE THREAD

**Issue by avallintine** [JacquesLucke/animation_nodes#785] opened 2017-09-12 00:45 UTC
I'm seeing a substantial frame rate drop during animation playback when an animation node tree exists in my scene with even a single node.

With a completely empty scene and an empty animation node tree I can get 60+ fps during playback. However, as soon as I add a node to the tree, my frame rate drops to ~30 fps. The type of node doesn't seem to matter. Adding additional nodes after the first doesn't seem to have much impact on the frame rate. Closing the node editor window has no effect.

My machine isn't the fastest in the world, but this seems unreasonable. Any idea what's going on?

**Comment by avallintine** [comment] 2017-09-12 00:51
Forgot to mention, I have the node tree set to update on "Frame Changed". If I uncheck all the update triggers, my frame rate goes back to normal.

**Comment by avallintine** [comment] 2017-09-12 01:35
Execution time for a tree with a single node is ~0.003 ms on my machine, but still my frame rate drops from ~60 to ~30.

**Comment by JacquesLucke** [comment] 2017-09-12 08:39
The thing is that AN currently makes a scene update and redraws the whole viewport when it finished its calculations. This is not really intended by Blender core developers but seems necessary. Without that I sometimes experienced crashes and other unexpected behaviors.

I can investigate this again but not too soon as I'm working on other AN related projects atm. I guess 30fps will still be good enough for working in Blender for now, so it is not a huge problem. 

AN only starts its calculations when there is at least one node to execute in the node tree, this is why it did not slow down when there were no nodes.

**Comment by avallintine** [comment] 2017-09-12 14:13
Yep, that's the problem. It's the call to redrawAll() in afterExecution(). I removed it and my frame rate went back to "normal". I first tried removing the call to scene.update() but it didn't have any noticeable effect on the frame rate.

Right, 30 fps might be good enough, but that's my best achievable with a _completely empty scene_. In another scene where I'm getting 25 fps normally, using AN drops that to 12 fps. Not great.

I'm going to try running without redrawing every execution and see what happens. Thank you for the explanation!

**Comment by JacquesLucke** [comment] 2017-09-12 16:08
Initially there was an option to turn this off in the user prefs but I removed it because it caused problems. I guess it depends on what you are doing. Maybe I'll bring it back at some point when I better know what's going on.

I'll close this for now, if you notice anything interesting feel free to reopen this issue.

**Closed by JacquesLucke** 2017-09-12 16:08 UTC
