### ISSUE TITLE
Sort Node does not work, indices "exception raised"

### ISSUE THREAD

**Issue by randomuser531** [JacquesLucke/animation_nodes#1039] opened 2019-03-06 20:20 UTC
I noticed "Sort" node does not output indices, or maybe i am doing it horribly wrong. I compiled  2.8 branch for myself, after omar told me its fixed this morning. But it wont output indices for me with my own build. I tested the newly compiled v2.1.4 test builds, it is the same there.
![an sort](https://user-images.githubusercontent.com/48297111/53910674-b1724f80-4054-11e9-8447-32bc741ad72c.jpg)

indices raises exception

![sort numbers](https://user-images.githubusercontent.com/48297111/53910825-16c64080-4055-11e9-9143-4e22cb8d7206.jpg)
Sorted Numbers works

**Comment by OmarSquircleArt** [comment] 2019-03-06 20:32
Can you include the output of the console?

**Comment by OmarSquircleArt** [comment] 2019-03-06 20:41
Also, in the developer panel, choose *Default* execution code method, press the *Write* button. Then include the contents of the `Execution Code` text block here.

**Comment by randomuser531** [comment] 2019-03-06 20:44
first this 
![sort2](https://user-images.githubusercontent.com/48297111/53912329-0912ba00-4059-11e9-8481-7d9a2bbd1662.jpg)

**Comment by randomuser531** [comment] 2019-03-06 20:45
import bpy, sys, numpy
import itertools
from time import perf_counter as getCurrentTime
from mathutils import Vector, Matrix, Quaternion, Euler
AN = animation_nodes = sys.modules.get('animation_nodes')
from animation_nodes.data_structures import *
from animation_nodes import algorithms
_node_execution_times = animation_nodes.execution.measurements.getMeasurementsDict()
nodes = bpy.data.node_groups['NodeTree.002'].nodes
_dkfco1b22vg1yws = nodes['Random Vector']
_4ptzj4jlqxjdkrd = nodes['Viewer.001']
_k3zlb95mwoa7x4e = nodes['Get List Element']
_x1nfdxy7y18qpar = nodes['Viewer']
_41tsl9mwq59o8cm = nodes['Separate Vector']
_i2ssexeqxhl662n = nodes['Sort']
_f6k3lx5hi8ae3i0 = nodes['Viewer.002']
_seed_dkf0 = _dkfco1b22vg1yws.inputs[0].getValue()
_count_dkf1 = _dkfco1b22vg1yws.inputs[1].getValue()
_scale_dkf2 = _dkfco1b22vg1yws.inputs[2].getValue()
_indices_k3z1 = LongList()
_fallback_k3z2 = _k3zlb95mwoa7x4e.inputs[2].getValue()



# Node: 'NodeTree.002' - 'Random Vector'
_randomVectors_dkf3 = _dkfco1b22vg1yws.calcRandomVectors(_seed_dkf0, _count_dkf1, _scale_dkf2)

# Node: 'NodeTree.002' - 'Viewer.001'
_4ptzj4jlqxjdkrd.execute(_randomVectors_dkf3)

# Node: 'NodeTree.002' - 'Get List Element'
if len(_randomVectors_dkf3) != 0:
    length = len(_randomVectors_dkf3)
    _elements_k3z3 = _k3zlb95mwoa7x4e.outputs[0].getDefaultValue()
    for i in _indices_k3z1:
        _elements_k3z3.append(_randomVectors_dkf3[i] if -length <= i < length else _fallback_k3z2)
else:
    _elements_k3z3 = Vector3DList.fromValues([_fallback_k3z2]) * len(_indices_k3z1)

# Node: 'NodeTree.002' - 'Viewer'
_x1nfdxy7y18qpar.execute(_elements_k3z3)

# Node: 'NodeTree.002' - 'Separate Vector'
_z_41t3 = _41tsl9mwq59o8cm.getAxisList(_randomVectors_dkf3, 'z')

# Node: 'NodeTree.002' - 'Sort'
if len(_z_41t3):
    _indices_i2s2 = LongList.fromNumpyArray(numpy.argsort(_z_41t3.asMemoryView()))
else:
    _indices_i2s2 = LongList()

# Node: 'NodeTree.002' - 'Viewer.002'
_f6k3lx5hi8ae3i0.execute(_indices_i2s2)

**Comment by OmarSquircleArt** [comment] 2019-03-07 04:34
I see. It seems the problem is a buffer type mismatch. On windows the output indices were `long long`. Fixed in 0832e2e . Can you try it?

**Comment by randomuser531** [comment] 2019-03-07 07:28
Hi Omar, it is working, thanks a lot!

**Closed** 2019-03-07 17:05 UTC
