### ISSUE TITLE
Error in Windows

### ISSUE THREAD

**Issue by karlisstigis** [JacquesLucke/animation_nodes#1066] opened 2019-03-26 21:11 UTC
Can't enable animation nodes.

Windows 10 Pro 64bit
Blender 2.8
animation_nodes_v2_1_4_windows_py37.zip

Exception in module register(): C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender\blender-2.80.0-git.adfdae3fc2f4-windows64\2.80\scripts\modules\addon_utils.py", line 384, in enable
    mod.register()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\__init__.py", line 172, in register
    auto_load.register()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\auto_load.py", line 28, in register
    bpy.utils.register_class(cls)
RuntimeError: Error: 'an_sequence_menu' doesn't contain '_MT_' with prefix & suffix

**Comment by OmarSquircleArt** [comment] 2019-03-27 06:16
Duplicate of #1061. Will probably be fixed tomorrow. Thanks for the report.

**Closed by OmarSquircleArt** 2019-03-27 06:16 UTC
