### ISSUE TITLE
Connecting Script node to Object output, crashes Blender

### ISSUE THREAD

**Issue by eric29** [JacquesLucke/animation_nodes#1065] opened 2019-03-26 18:35 UTC
Operating system: Windows 7
Graphics card: GT750M
Animation Nodes version: 2.1.4
Blender version: 2.80, 07f6be87a97e - March25 build (but crashes on other version of 2.8 I've tries as well)

Not sure if this is an issue with Animation Nodes or Blender, but since it's happening with Animation Nodes, I have to submit the issue here first.

Reproduce:
1. Create a text object in the scene.
2. In Animation Nodes, create a Script node - New output = "Text"
3. Create an "Object output" node, and link text object in scene.
4. Drag output of script to Object text node (or any of it's inputs actually)
5. Bender crashes

**Comment by OmarSquircleArt** [comment] 2019-03-26 19:03
Closing because it is a duplicate of #1013.

**Closed by OmarSquircleArt** 2019-03-26 19:03 UTC
