### ISSUE TITLE
animation nodes 2.1.4 fails with blender 2.8 on Linux

### ISSUE THREAD

**Issue by klankschap** [JacquesLucke/animation_nodes#1146] opened 2019-07-13 08:01 UTC
Animation Nodes 2.1.4 fails to work with Blender 2.8 RC1 on Linux
The simple Hello World will not work:
e.g. Integer Input (with value set to 2) -> Viewer (shows None)

**Comment by 3DSinghVFX** [comment] 2019-07-13 08:40
Are you using the latest build of animation nodes for Linux? Please try the latest build of animation nodes https://github.com/JacquesLucke/animation_nodes/releases

**Comment by TaOuch** [comment] 2019-07-13 12:18
i have also this issue since a couple of weeks. nothing inside Animation Node editor seems to work. not even the Viewer (as mentioned to klankschap)
i was using AN 2.1.3
following your comment i have built AN 2.1.4 in Linux, but still nothing is happening. 

from a new project with the default cube:
- i open the AN editor, create a new NodeTree, open the Toolbox
- add an Integer Input to the Viewer -> the Viewer Node display : None. 
note that the Viewer node has a dark grey color
- inside the Toolbox i Print the execution

```
Traceback (most recent call last):
  File "/home/taouch/.config/blender/2.80/scripts/addons/animation_nodes/operators/output_execution_code.py", line 14, in execute
    code = getCurrentExecutionCode(lineNumbers = True)
  File "/home/taouch/.config/blender/2.80/scripts/addons/animation_nodes/operators/output_execution_code.py", line 44, in getCurrentExecutionCode
    network = bpy.context.active_node.network
  File "/home/taouch/.config/blender/2.80/scripts/addons/animation_nodes/base_types/nodes/base_node.py", line 539, in network
    return getNetworkWithNode(self)
  File "/home/taouch/.config/blender/2.80/scripts/addons/animation_nodes/tree_info/__init__.py", line 176, in getNetworkWithNode
    return _networks.networkByNode[node.toID()]
KeyError: ('NodeTree', 'Viewer')

location: <unknown location>:-1
```
- in the Developer tab of the Toolbox, i set Function to "Update Everything" then press the button "Profile" -> the Viewer node becomes light grey (like the Integer Input node)

- from there if i press the button "Execute Node Tree", the Viewer node receive the Integer. but the "Auto Execution" doesnt work. i have to press the "Execute Node Tree" every time i change the Integer Input Node

- note that if i add any nodes, they all seem to have this dark grey color. i have to press the button "Profile"  to enable them first, and then "Execute Node Tree" to execute the NodeTree

```
**System Information**
Operating system: Linux-5.0.0-20-generic-x86_64-with-debian-buster-sid 64 Bits

**Blender Version**
Broken: version: 2.80 (sub 74), branch: master, commit date: 2019-07-12 17:50, hash: `rBe3c586e262dd`
```

**Comment by klankschap** [comment] 2019-07-13 13:05
On 13-07-19 10:40, Kuldeep Singh wrote:
> Are you using the latest build of animation nodes for Linux? Please try
> the latest build of animation nodes
> https://github.com/JacquesLucke/animation_nodes/releases

yes, the latest build, v2.1.4 for blender 2.8
d85a67ffdca54e6fb359442d10f54adf.zip

.F

**Comment by 3DSinghVFX** [comment] 2019-07-13 13:13
@klankschap Can you please upload the screenshot of error message? Actually, I have tested this build of AN on the latest Blender RC1 (13-07-2019) build and it is working.

**Comment by 3DSinghVFX** [comment] 2019-07-13 13:17
@TaOuch Please try the build from this link https://github.com/JacquesLucke/animation_nodes/releases. If you get any error message please upload the screenshot.

**Comment by klankschap** [comment] 2019-07-13 15:22
On 13-07-19 15:13, Kuldeep Singh wrote:
> @klankschap <https://github.com/klankschap> Can you please upload the
> screenshot of error message? Actually, I have tested this build of AN on
> the latest Blender RC1 (13-07-2019) build and it is working.
> 

So now 2.1.4 seems to work as intended.
The thing was, that 2.1.3 stopped working and removing it without
relaunching blender was not enough to replace it with the new 2.1.4
version.

I do notice that with this new 2.1.4 version, the 'Auto Execution' needs
the 'Always' option checked to respond to changes of movement of
underlying objects.


.F

**Comment by TaOuch** [comment] 2019-07-13 15:48
> @TaOuch Please try the build from this link https://github.com/JacquesLucke/animation_nodes/releases. If you get any error message please upload the screenshot.

- i have downloaded the lastest source for AN v2.1.4 test builds 
- i unzipped the zip
- i copied paste the animation_nodes directory from the source to my Bledner 2.80 addon directory
- in Blender when trying to enable for the first time the plugin

![Screenshot from 2019-07-13 17-28-48](https://user-images.githubusercontent.com/34437611/61173491-5cab8c00-a594-11e9-93d4-18f7b410f341.png)

- so i have deleted the animation_nodes directory inside my blender2.80 addon 
- i have build the addon from the source with this command
python3 setup.py build --export

- then in Blender addon setting, i had the newly created zip (no error this time)

![Screenshot from 2019-07-13 17-46-50](https://user-images.githubusercontent.com/34437611/61173632-3b4b9f80-a596-11e9-8d61-99f6441eb2b7.png)

- in AN editor, i create a Integer Node -> Viewer Node. No error. but also nothing happening

(note that i m daily updating Blender 2.80, and that AN stopped working after a Blender update)

![Screenshot from 2019-07-13 17-44-14](https://user-images.githubusercontent.com/34437611/61173618-03dcf300-a596-11e9-9b23-2c8ef9ffdb66.png)

**Comment by 3DSinghVFX** [comment] 2019-07-13 16:04
To compiled build the animation nodes, the full command is `python3.7 setup.py  build --export --noversioncheck`, if you type _python3_ sometimes it takes as _python3.5_. Another thing is, you do not need to unzip the downloaded AN build file, you can install the zip file directly from the _preference_ menu.

**Comment by TaOuch** [comment] 2019-07-13 17:59
@3DSinghVFX. 

- Ok. Compiling the build with your command did not change anything. (system-wide, i have only Python 2.7.16 and Python 3.7.3)

- Unfortunately, installing the zip directly doesnt work :)
https://github.com/JacquesLucke/animation_nodes/archive/v2.1.4.zip

If i install the zip file directly from the _preference_ menu, Blender doesnt see AN in his list. There is no  ___init__.py_ in the root of the archive. 

After the compiled build i m doing, i m able to import the newly created zip ... but still nothing happen ... :(

- if klankschap has managed to solve his problem ... then it means i m the problem :) and most likely there is something wrong with my config (and wouldnt blame you if you dont want to spend more time on this)

here is the compilation_info.json

```
{
  "Cython.__version__": "0.29.12",
  "date": 1563039764,
  "os.name": "posix",
  "sys.api_version": 1013,
  "sys.platform": "linux",
  "sys.version": "3.7.3 (default, Apr  3 2019, 05:39:12) \n[GCC 8.3.0]",
  "sys.version_info": [
    3,
    7,
    3,
    "final",
    0
  ]
}
```

**Comment by 3DSinghVFX** [comment] 2019-07-13 18:33
The zip file you have mentioned is the source code, not the compiled build, so it will not work. You can download the **compiled build of AN zip file** for Linux for Blender 2.8x from here: https://blender.community/c/graphicall/Wdbbbc/ which you can install from the preference menu.

**Comment by TaOuch** [comment] 2019-07-13 18:51
Ha Ok! Now it works :)
You can not imagine how much time i spent on this graphicall looking for a link for AN 2.1.4 ... if you dont know it, the download button is not that pretty obvious ...
Thanks a lot

**Comment by 3DSinghVFX** [comment] 2019-07-13 20:45
@klankschap If you do not want to activate the **Always** auto execution then make the underlying object as a **Trigger** based on the property you are changing. You can read more about **Auto Execution and Triggers** https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/getting_started/execution.html?highlight=auto%20execution. Otherwise you have to enable the auto execution **Always** option to see the live response when you are changing the underlying object in the viewport and this is also true for the older version of AN.

**Comment by 3DSinghVFX** [comment] 2019-07-13 20:49
@OmarSquircleArt I think this issue is resolved. Please have a look.

**Comment by OmarSquircleArt** [comment] 2019-07-13 21:14
@3DSinghVFX Which issue are we talking about here?

Execution triggers have been rewritten, and it probably breaks backward compatibility, so if you are using an old file, this is probably the cause.

**Comment by 3DSinghVFX** [comment] 2019-07-13 21:34
Omar, I mean this "animation nodes 2.1.4 fails with blender 2.8 on Linux" is resolved.

**Comment by WenyinWei** [comment] 2019-07-14 00:56
![image](https://user-images.githubusercontent.com/33152225/61177977-e56a0c80-a614-11e9-9d31-805bdd8d3913.png)

@3DSinghVFX Hello, would you mind having a look at my similar activation error? After I activated the add-on in the add-on menu, it just failed, saying that some modules are missing.

**Comment by WenyinWei** [comment] 2019-07-14 01:04
Oh, sorry, it is fixed very easily by removing the remaining folder of last version AN. It can not be removed by clicking on the `remove` button but to delete the AN add-on folder directly.

**Comment by OmarSquircleArt** [comment] 2019-07-14 08:49
@3DSinghVFX Yes, this has already been resolved.

**Comment by OmarSquircleArt** [comment] 2019-07-14 08:50
Is this issue resolved? Should we close it?

**Comment by 3DSinghVFX** [comment] 2019-07-14 11:12
Yes, it is resolved. Please close this.

**Closed** 2019-07-14 11:38 UTC
