### ISSUE TITLE
Proposal: A "spline from text object" node, or a replacement for "

### ISSUE THREAD

**Issue by VladFromRomania** [JacquesLucke/animation_nodes#1606] opened 2020-12-12 19:17 UTC
At the moment, only procedural way to convert text to curves is to use the "Separate text object" node. Problem with that approach:
It is not really procedural and does not work well with "Decompose text" node.

**Comment by OmarEmaraDev** [comment] 2020-12-12 20:07
Duplicate of #1607.

**Closed by OmarEmaraDev** 2020-12-12 20:07 UTC
