### ISSUE TITLE
Losing control of objects.

### ISSUE THREAD

**Issue by limkork** [JacquesLucke/animation_nodes#1373] opened 2020-03-21 17:05 UTC
Hi, 

I am following Zach Hixson's tutorial on "sound falloff nodes" and after making changes to the "sound falloff" node, my objects do no longer react to the soundtrack or any other input that was put in before it, this also happened in an earlier tutorial, it is like AN has been deactivated and I can not keep working on my objects. 

I have tried to save and restart Blender, but no luck. I'm on 2.82.

thanks

**Comment by OmarEmaraDev** [comment] 2020-03-21 17:22
We can't really know what the problem is from just your description. Can you provide more details? A screenshot of the node tree? Any errors in the terminal?

**Comment by limkork** [comment] 2020-03-21 17:54
![SoundFalloff](https://user-images.githubusercontent.com/26370504/77233044-1ab3fa80-6ba5-11ea-9734-f15adaf087ca.jpg)


Here is my node tree, and by terminal, do you mean the python console of the info? Sorry, not much of a "behind-the-UI" guy.

**Comment by limkork** [comment] 2020-03-21 17:59
or do you mean to launch from the command line?

**Comment by OmarEmaraDev** [comment] 2020-03-21 18:21
The red border means there is a fatal error. This error is printed on the console, which you can open from Window -> Toggle System Console.

**Comment by limkork** [comment] 2020-03-21 20:40
Read prefs: C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\config\userpref.blend
found bundled python: E:\Apps\Blender\2.82\2.82\python
measureit_arch: Imported multifiles
Warning: class MeasureitArchIndex contains a property which should be an annotation!
C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MeasureIt-ARCH-master\measureit_arch_dimensions.py:40
    assign as a type annotation: MeasureitArchIndex.glidx
Warning: class MeasureitArchFaces contains a property which should be an annotation!
C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MeasureIt-ARCH-master\measureit_arch_dimensions.py:51
    assign as a type annotation: MeasureitArchFaces.glface
Warning: class MEASUREIT_ARCH_OT_addtolinegroup contains a property which should be an annotation!
C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MeasureIt-ARCH-master\auto_load.py:28
    assign as a type annotation: MEASUREIT_ARCH_OT_addtolinegroup.tag
Warning: class MEASUREIT_ARCH_OT_addlinebyproperty contains a property which should be an annotation!
C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MeasureIt-ARCH-master\auto_load.py:28
    assign as a type annotation: MEASUREIT_ARCH_OT_addlinebyproperty.tag
    assign as a type annotation: MEASUREIT_ARCH_OT_addlinebyproperty.calledFromGroup
Warning: class MEASUREIT_ARCH_OT_addnotebutton contains a property which should be an annotation!
C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MeasureIt-ARCH-master\auto_load.py:28
    assign as a type annotation: MEASUREIT_ARCH_OT_addnotebutton.tag
Warning: class MEASUREIT_ARCH_OT_removefromlinegroup contains a property which should be an annotation!
C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MeasureIt-ARCH-master\auto_load.py:28
    assign as a type annotation: MEASUREIT_ARCH_OT_removefromlinegroup.tag
Warning: class MEASUREIT_ARCH_OT_listdeletepropbutton contains a property which should be an annotation!
C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MeasureIt-ARCH-master\auto_load.py:28
    assign as a type annotation: MEASUREIT_ARCH_OT_listdeletepropbutton.tag
Warning: class MEASUREIT_ARCH_OT_deletepropbutton contains a property which should be an annotation!
C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MeasureIt-ARCH-master\auto_load.py:28
    assign as a type annotation: MEASUREIT_ARCH_OT_deletepropbutton.tag
    assign as a type annotation: MEASUREIT_ARCH_OT_deletepropbutton.item_type
    assign as a type annotation: MEASUREIT_ARCH_OT_deletepropbutton.is_style
Warning: class MEASUREIT_ARCH_OT_addsegmentortobutton contains a property which should be an annotation!
C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MeasureIt-ARCH-master\auto_load.py:28
    assign as a type annotation: MEASUREIT_ARCH_OT_addsegmentortobutton.tag
register_class(...):
Warning: 'MeasureitArchRenderPanel' doesn't contain '_PT_' with prefix & suffix
Warning: class MEASUREIT_ARCH_OT_rendersegmentbutton contains a property which should be an annotation!
C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MeasureIt-ARCH-master\auto_load.py:28
    assign as a type annotation: MEASUREIT_ARCH_OT_rendersegmentbutton.tag
register
Registered MESHmachine 0.6.10 with 2 plug libraries
 ┬╗ plug library: Examples
 ┬╗ plug library: MyPlugs
Registered MACHIN3tools 0.3.12 with 11 tools, 7 pie menus and 1 context menu
Registered Animation Nodes
Traceback (most recent call last):
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MACHIN3tools\operators\clipping_toggle.py", line 58, in update_state
    view.clip_start = self.minimum
AttributeError: 'NoneType' object has no attribute 'clip_start'
File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MACHIN3tools\operators\clipping_toggle.py", line 46, in update_state
Traceback (most recent call last):
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MACHIN3tools\operators\clipping_toggle.py", line 58, in update_state
    view.clip_start = self.minimum
AttributeError: 'NoneType' object has no attribute 'clip_start'
File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MACHIN3tools\operators\clipping_toggle.py", line 46, in update_state
Warning: TypeError('bpy_struct: item.attr = val: enum "" not found in (\'OBJECT\', \'EDIT\', \'POSE\', \'SCULPT\', \'VERTEX_PAINT\', \'WEIGHT_PAINT\', \'TEXTURE_PAINT\', \'PARTICLE_EDIT\', \'EDIT_GPENCIL\', \'SCULPT_GPENCIL\', \'PAINT_GPENCIL\', \'WEIGHT_GPENCIL\')')
Warning: TypeError('bpy_struct: item.attr = val: enum "" not found in (\'OBJECT\', \'EDIT\', \'POSE\', \'SCULPT\', \'VERTEX_PAINT\', \'WEIGHT_PAINT\', \'TEXTURE_PAINT\', \'PARTICLE_EDIT\', \'EDIT_GPENCIL\', \'SCULPT_GPENCIL\', \'PAINT_GPENCIL\', \'WEIGHT_GPENCIL\')')
Warning: property 'select' not found in keymap item 'TEXT_OT_selection_set'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'






Traceback (most recent call last):
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\units.py", line 58, in setupExecutionUnits
    unit.setup()
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 26, in setup
    exec(self.setupCodeObject, self.executionData, self.executionData)
  File "setup: 'NodeTree'", line 41, in <module>
IndexError: bpy_prop_collection[index]: index 11 out of range, size 11
Traceback (most recent call last):
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\utils\handlers.py", line 71, in frameChangedPost
    handler(scene, depsgraph)
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\events.py", line 38, in frameChanged
    event_handler.update({"Frame"})
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\utils\recursion.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\event_handler.py", line 23, in update
    executeNodeTrees(nodeTrees)
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\auto_execution.py", line 13, in executeNodeTrees
    nodeTree.autoExecute()
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\base_types\node_tree.py", line 82, in autoExecute
    self._execute()
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\base_types\node_tree.py", line 100, in _execute
    success = unit.execute()
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 73, in raiseNotSetupException
    raise ExecutionUnitNotSetup()
animation_nodes.problems.ExecutionUnitNotSetup
Measureit-ARCH: Cleaning Phantom Objects
Warning: Path 'C:\Users\lasse\Downloads\Poppy - I Disagree (Official Music Video).mp3' cannot be made relative
Warning: Path 'C:\Users\lasse\Downloads\Poppy - I Disagree (Official Music Video).mp3' cannot be made relative
Warning: Total files 2 | Changed 0 | Failed 2
Read blend: E:\Design\Experiments\untitled.blend
Read blend: E:\Design\Experiments\untitled.blend
Info: Deleted 1 data-block(s)

Read blend: E:\BlenderTemps\untitled_16380_autosave.blend
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\RenameObjects.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\build.py'
multiple addons with the same name:
  'E:\\Apps\\Blender\\2.82\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
  'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\magic_uv\\__init__.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\properties.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\lasse\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\util.py'

**Comment by limkork** [comment] 2020-03-21 21:01
ok, so after looking at that console, I deleted a bunch of the addons that were giving bad performance issues, and now it seems to be working again.

thanks for the help, that console sure is handy!

**Comment by limkork** [comment] 2020-03-21 21:08
ok, so it's not over yet, as I went to change a setting in the "sound falloff", I got a red border in my viewport and this message in the console.

Traceback (most recent call last):
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\units.py", line 58, in setupExecutionUnits
    unit.setup()
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 26, in setup
    exec(self.setupCodeObject, self.executionData, self.executionData)
  File "setup: 'NodeTree'", line 49, in <module>
IndexError: bpy_prop_collection[index]: index 11 out of range, size 11
Traceback (most recent call last):
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\utils\handlers.py", line 71, in frameChangedPost
    handler(scene, depsgraph)
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\events.py", line 38, in frameChanged
    event_handler.update({"Frame"})
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\utils\recursion.py", line 12, in wrapper
    result = function(*args, **kwargs)
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\event_handler.py", line 23, in update
    executeNodeTrees(nodeTrees)
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\auto_execution.py", line 13, in executeNodeTrees
    nodeTree.autoExecute()
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\base_types\node_tree.py", line 82, in autoExecute
    self._execute()
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\base_types\node_tree.py", line 100, in _execute
    success = unit.execute()
  File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\animation_nodes\execution\main_execution_unit.py", line 73, in raiseNotSetupException
    raise ExecutionUnitNotSetup()
animation_nodes.problems.ExecutionUnitNotSetup

**Comment by OmarEmaraDev** [comment] 2020-03-22 10:04
You you try to make a minimal file that reproduces the problem easily?

**Comment by limkork** [comment] 2020-03-22 11:25
Do you mean to upload a blender file with this setup?

**Comment by OmarEmaraDev** [comment] 2020-03-22 11:27
Yes. Try to make a setup that is as simple as possible, describe in details the steps to replicate the error using this setup, and upload the blend file here.

**Comment by limkork** [comment] 2020-03-22 11:46
https://drive.google.com/file/d/1fpXQM6YYxZlWTDabfsPvEJ-ihh7uVtG1/view?usp=sharing

So the details to replicate are as follows.

In the "sound falloff" node, if I change the type from "spectrum" to "average" it will create an error, but it did let me do it once or twice, but 9/10 i will fail.

**Comment by OmarEmaraDev** [comment] 2020-03-22 12:48
Fixed in 84566d4.

**Closed by OmarEmaraDev** 2020-03-22 12:48 UTC
Labels: bug
