### ISSUE TITLE
Matrix Rotation Issue?

### ISSUE THREAD

**Issue by LeonCheung** [JacquesLucke/animation_nodes#690] opened 2017-04-18 16:16 UTC
As mentioned in #688 , I also encountered a strange behavior when trying to rotate things over and over in a case like [this](https://blender.stackexchange.com/a/77938/696) (Rubik's cube animation). Download and open the file, jump to frame 311, you can see the **unit_07** object was actually rotated towards the opposite direction to others, which shouldn't be expected.

![reversed rotation](https://cloud.githubusercontent.com/assets/494788/25140678/bb5752c2-2493-11e7-8219-77d25520e38b.png)

What is interesting is, it can be parcially solved by snapping values to a certain dergree:

![fix](https://cloud.githubusercontent.com/assets/494788/25140911/6d2dadfc-2494-11e7-9665-ade7c650e30b.png)

However, it only solves the problem around that frame, and the same issue will occassionally occur elsewhere then. So it can't be a "one time for all" fix.

I'm sure that all rotations are either 0d, ±90d or ±180d, with no decimals. Not sure if this is something about precision.

**Comment by JacquesLucke** [comment] 2017-04-18 16:34
Can you try to simplify the file?
Having just one object that moves, without not needed nodes, would make finding the root cause of thr problem much easier

**Comment by LeonCheung** [comment] 2017-04-18 18:44
Well, not that easy I'm afraid... I can delete other objects, but almost all nodes contributes to the whole setup, as well as the final result, will try my best however, will try tomorrow :zzz: .

**Comment by LeonCheung** [comment] 2017-04-19 05:28
Finally tried to narrow it. I think the problem below may cause what I've encountered:

![diff](https://cloud.githubusercontent.com/assets/494788/25164412/4c279388-2503-11e7-96ca-6d8b7b74e58a.png)

As tested when rotation angle >= 180d, it will go along the opposite direction, while it doesn't happen with transform output node.

To be honest I really don't know if this is how matrix exactly works anyway....

[Test File (created with v1.6 master)](https://drive.google.com/file/d/0B1ojv5B6Lb-3bnp3NTlWc0docmc/view?usp=sharing)

**Comment by JacquesLucke** [comment] 2017-04-19 09:08
ah thx, will look at the file a bit later, just got a little idea:
Maybe the matrix maps the 180 degree to -180. Which makes the Animate Matrix go the other way around.
Can you debug the Rotation Matrix node to see if the matrix changes a lot when going from 179 to 180 degree?

**Comment by lemonAcidjuice** [comment] 2017-04-19 13:53
Here is a [test file](http://blend-exchange.giantcowfilms.com/b/3169/), made using the Cython branch.

It is a simplified version of the cube rotation I used in the issue #688.

First some preliminary information: 
- Depending on the start frame you are on at the beginning (here either 0 or 1), the result is not the same (and that's probably normal, because we have an additional frame change).
- But starting from frame 0 (which I took as reference), the result is not the same either you are using the right arrow key (to jump frame by frame) or using alt+A

Now, in this configuration, past frame 181: 
- The rotation is identity
- The input matrix is 'as it is' (say M)
- The result "identity * M" is M
- But setting M as matrix output for the object rotates it!
(look at the debug nodes on the right)

And, more: this is happening only if running with "alt+A" and this does not occur if using the right arrow key (in this last case, the calculation is ok... same thing on #688 file).

**Comment by LeonCheung** [comment] 2017-04-19 16:33
Like this?

![debug](https://cloud.githubusercontent.com/assets/494788/25191084/02a2e376-2561-11e7-837c-3fd25f97a567.gif)

**Comment by JacquesLucke** [comment] 2017-04-19 21:07
Thanks, yes that is what I meant, but it did not help..

So I think the problem is (and you noticed something like this already) that a matrix just stores a cannot store things like "rotate 200 degree along the X axis". Instead it stores "rotate -160 degrees along the X axis". You can see that by decomposing the matrix again, the angles never go over 180 degree.

Usually you don't need to care about this but it becomes very noticeable when  you use the Animate Matrix node. The exact procedure how it works is currently part of Blender but I think it always takes the shortest route from the start to end location.

Solving the problem is relatively easy in theory. Just don't use the Animate Matrix node at all. Instead animate the rotation before converting it into a matrix and then combine the matrices. This is also the reason why the new Offset Matrices node has Loc/Rot/Scale inputs instead of just one matrix. 
Fortunately this solution also has better performance, animating a matrix in a "good" is quite a difficult task which usually involves decomposing the matrix, interpolate the decomposed values, compose it again. Not sure how it is implemented in Blender but I'm sure it is similiar. (Just interpolating the individual values would result in weird stretching)

Currently there is not a good node which allows you to transform a single matrix similar to the Offset Matrices node (which intentionally is only lists, because falloffs or best when applied to lists). I can develop such a node of course (maybe as part of the new Transform Matrix node).

**Comment by lemonAcidjuice** [comment] 2017-04-20 06:09
@JacquesLucke have you seen the post I sent just before?

There is no "Animate Matrix" node but the problem is still there. And what about this difference in the behavior between alt+A animation and right key/frame by frame animation?

**Comment by LeonCheung** [comment] 2017-04-20 16:14
@JacquesLucke Thanks for the discussion, it really helps in solving the problem!

However, the idea you advised doesn't work well (see the setup below), I think it might be related with euler rotation order:
![don](https://cloud.githubusercontent.com/assets/494788/25240207/d498eeb6-2624-11e7-8c8b-7b2006aede91.png)

Anyway, good news is, I solved it with the similar idea:
![work](https://cloud.githubusercontent.com/assets/494788/25240197/d1019c4e-2624-11e7-9506-2445bce2c160.png)

Thanks again for the inpiration! It works perfect. Now, 70 functional nodes for a not-so-bad [Rubik's Cube Animator](https://drive.google.com/open?id=0B1ojv5B6Lb-3U3ZSRUJQVE1Ub3M) setup. :)

**Comment by JacquesLucke** [comment] 2017-04-20 19:52
@lemonAcidjuice: Sorry I have not seen this for some reason.. Just looked at your setup and I think a fundamental flaw is that you use the transformation from the frame before to calculate the new transformation. That is something you should not do because if you do (in almost all cases), the result depends on when and how often the node tree is executed.
Sometimes AN cannot guarantee that the node tree is only executed once when you change the frame manually. Therefor the output of the node tree should only depend on the current frame and not on the state from the frame before.

@LeonCheung: Congrats on finishing this long lasting project! Just tested it, works really well. The final solution you used was actually what I thought (and tried to explain) as well. The thing with decompose/animate/compose is just what is internally done. Unfortunally rotating an euler around a specific axis is not very easy as you noticed. You can't just add the angles together.

**Comment by lemonAcidjuice** [comment] 2017-04-21 18:01
@JacquesLucke thanks for your reply. I see what you mean in the previous post, but either I've not understood (possible as my english is far from perfect), or this is not the point. In the sample file, past frame 181, the calculation gives a result that is exactly the same world_matrix as the input but the object continues to rotate (only on itself and not around the center). I do not get why!!

**Comment by JacquesLucke** [comment] 2017-04-21 18:55
For some reason this is not the case here, the cube does not move after frame 180. Can you maybe resend the file? Maybe I'm in the wrong file accidentally.

**Comment by lemonAcidjuice** [comment] 2017-04-23 14:15
Here is the file again: [<img src="https://blend-exchange.giantcowfilms.com/embedImage.png?bid=3205" />](http://blend-exchange.giantcowfilms.com/b/3205/). It is weird: I told before that all was well using keyboard arrow key, but this is not the case anymore. The cube keeps rotating in both cases. I've also checked that with AN 1.6 (I was previously with Cython branch): same thing. For Blender: PC 2.78c. If the cube still does not rotate for you, I will reinstall all... thanks to tell me when you can.

**Comment by JacquesLucke** [comment] 2017-04-28 19:33
I totally see what you mean... And I have to admit that I have no idea atm what can cause this. Usually I'd say this is a numerical problem but the artifacts seem to be too large for that.

In general we can say that you should never use the Object Matrix Input and the Object Matrix Output node on the same object in the same node tree.

**Comment by LeonCheung** [comment] 2017-04-30 07:32
@lemonAcidjuice If you toggle "Always" on, you can see the matrix keeps updating even if frame isn't changed. That's why the ID Key system exists, in order to use a type of static value as the base of further calculation, instead making an endless loop iteration like what shows in your file, same as what happens in your file on SE.

Basically speaking, the animation interpolation there you saw is not real, kinda"fake", which caused by this kind of frame-by-frame iteration. Actually the "frame info" there doesn't function as variable, but more like a trigger for updating the scene, that's why there's no difference between **Alt A** and **Shift Alt A** in your file.

Maybe the basic concept of your solution can be doable anyway, but it seems very tricky, since you haven't use any "Animate XXX" nodes to define animation for each move. Will see what I can do by following the concept you used, and try to modify your setup. (I'm also not so satisfied with my solution either due to the performance anyway. but that's what I got so far) But that should be another topic. Agree? :)

**Comment by lemonAcidjuice** [comment] 2017-05-04 13:40
@LeonCheung yes and thanks. I'll try to rework on it based on the information you provided.

**Comment by JacquesLucke** [comment] 2017-05-04 15:30
I'll close this for now. If you experience other problems, please open a new issue.

**Closed by JacquesLucke** 2017-05-04 15:30 UTC
