### ISSUE TITLE
Separate Text Object

### ISSUE THREAD

**Issue by cflanagan** [JacquesLucke/animation_nodes#988] opened 2018-12-29 16:02 UTC
The latest version of Blender and AN 2.1 -- Clicking Update on the Separate Text Object throws an error.

![blender2 8](https://user-images.githubusercontent.com/3866207/50540064-5f8ae600-0b48-11e9-8a2e-95cc0ab4c8a9.png)
![errormsg](https://user-images.githubusercontent.com/3866207/50540068-63b70380-0b48-11e9-86e0-7b666b7e871b.png)

**Comment by OmarSquircleArt** [comment] 2018-12-29 16:17
Thanks for the report. We are aware about this. Closing because it is duplicate of #977.

**Closed by OmarSquircleArt** 2018-12-29 16:17 UTC
