### ISSUE TITLE
Baking particle systems with auto execution on crashes blender or breaks animation nodes.

### ISSUE THREAD

**Issue by LahiruVIP** [JacquesLucke/animation_nodes#1242] opened 2019-11-25 13:42 UTC
I used a get particle system from object. When you bake the particle system physics with auto execution: "always" it crashes blender. When on other modes of auto execution, Animation nodes stops working completely and also doesn't work in any other files that uses AN. To make AN working again, blender needs to be closed and opened again. Only work around is to disable auto execution before baking the particle systems.

**Comment by OmarEmaraDev** [comment] 2019-11-25 13:44
The crash is probably caused by #1200. Do you see a red border around the node tree?

**Comment by LahiruVIP** [comment] 2019-11-25 14:00
No red border is showing up. Also change in the problem doesn't break animation nodes any more and only crashes blender when either auto execution "always"  or "frame changed" are enable other modes are fine.

**Comment by OmarEmaraDev** [comment] 2019-11-25 14:01
Can you attack the contents of the crash.txt file?

**Comment by LahiruVIP** [comment] 2019-11-25 14:37
blender doesn't save a crash.txt file for me.

**Comment by OmarEmaraDev** [comment] 2019-11-25 14:42
Ok, I will try to replicate the issue on my end.

**Comment by OmarEmaraDev** [comment] 2019-12-05 16:25
I can't replicate this issue. Can you update your Blender build or share a blend file?

**Comment by LahiruVIP** [comment] 2019-12-05 16:36
Here is the blend file
[plexus_nodes_4.zip](https://github.com/JacquesLucke/animation_nodes/files/3927990/plexus_nodes_4.zip)

**Comment by LahiruVIP** [comment] 2019-12-05 16:37
Also extra information i use AN version 2.1.4 .

**Comment by OmarEmaraDev** [comment] 2019-12-05 16:43
I just replicated the issue. This seems like a blender bug. Please report it to the Blender developer.

**Comment by OmarEmaraDev** [comment] 2020-02-17 18:04
Fixed in #1294 and b1ac938.

**Closed by OmarEmaraDev** 2020-02-17 18:04 UTC
