### ISSUE TITLE
Script crashes on connecting anything to its outlet

### ISSUE THREAD

**Issue by cnisidis** [JacquesLucke/animation_nodes#1144] opened 2019-07-12 23:11 UTC
After introducing a script node without doing anything else than creating an outlet of type "Float" and connecting Viewer or any Float type on it Blender crashes.

**Comment by OmarSquircleArt** [comment] 2019-07-13 07:31
Duplicate of #1013.

**Closed by OmarSquircleArt** 2019-07-13 07:31 UTC
