### ISSUE TITLE
During animation, property change break the node-tree. 

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1308] opened 2020-02-04 18:11 UTC
Hi...
I have found that if I change the property of the Distribute Matrices node during the animation break the node-tree. This sometimes also occur for Create List node if delete all the input of the node. 

Add the Distribute Matrices node then play the animation. While playing when you change the property e.g., Grid to Mesh one or more times then it breaks the node-tree, 
![Screenshot from 2020-02-04 23-37-55](https://user-images.githubusercontent.com/30294746/73773065-72d69f00-47a7-11ea-9b7e-6b33acb6a60c.png)

This is an error on the terminal:
![Screenshot from 2020-02-04 23-25-50](https://user-images.githubusercontent.com/30294746/73772975-386d0200-47a7-11ea-8209-f8612f822398.png)

**Comment by OmarEmaraDev** [comment] 2020-02-05 12:21
I can replicate the issue. Will look into it.

**Comment by 3DSinghVFX** [comment] 2020-02-05 12:32
Okay.

**Comment by OmarEmaraDev** [comment] 2020-02-05 13:05
Seems to be a regression from 081819d.

**Comment by OmarEmaraDev** [comment] 2020-02-06 10:37
Fixed in 1f04619.

**Closed by OmarEmaraDev** 2020-02-06 10:37 UTC
Labels: bug

**Comment by 3DSinghVFX** [comment] 2020-02-06 12:33
Thanks :)
