### ISSUE TITLE
Installationproblem with AN 2.0.0 / AN 2.0.2

### ISSUE THREAD

**Issue by SVANy** [JacquesLucke/animation_nodes#729] opened 2017-07-12 12:18 UTC
Hi Jacques,
you’ve asked me to create an issue here on Github because of my heartache with AN.
So first, here are my datas:

Me: I’m a “Kraut” and I’m a newbee in Linux and Blender. With Blender I work for about two years, with AN about one month.
       
OS Version: Suse Linux 4.4.73
Blender Version: 2.78c / I’ve downloaded “Tarball.bz2” 64Bit from blender.org, so no need for me to compile by myself
Python Version: 3.4.6 [GCC]

With Animation Nodes 1.6 I had no problems at all with installation.
To install Version 2.0 I first deactivated the old version, restarted Blender, removed the old version, and to be sure I restarted Blender again before I installed the new version.

Same procedure with every new install.

I’ve tried those versions from graphicall:
- Animation Nodes 2.0 beta by Thomas Beck (12270) (User preferences told me it’s Vers. 1.7.5) 
- Animation Nodes 2.0 Beta Cython by Gottfried Hofmann(12273) (Here too, user preferences told me it’s Vers. 1.7.5)
- Animation Nodes 2.0 Beta (another Linux build) by jasperge (12309)
- Animation Nodes 2.0 Beta (another Linux build) by jasperge (12337) (User preferences told me it’s Vers. 2.0.2)

After installing it was not possible to activate a single version. With trying to activate everytime I got a little black screen with errormessage.
With the version by Thomas Beck (12270) I  unfortunately got an unreadable message, because the message was cutted on the left half side.

With all three other versions I got the same message as follows:

Traceback (most recent call last):
  File "/………./blender-2.78c-linux-glibc219-x86_64/2.78/scripts/modules/addon-utils.py", line 330, in enable mod = __import__(module_name)
  File "/………./.config/blender/2.78/scripts/addons/animation_nodes/__init__.py", line 106, in <module>
    raise Exception(message)
Exception:
……….

I hope, with these informations I can help you to help me to get back my love AN. 
Many thanks in anticipation.

**Comment by JacquesLucke** [comment] 2017-07-12 13:14
I'm not at home atm so I can't check it in detail yet.

One problem might be that your Blender version uses Python 3.4.x
The builds are for Python 3.5.x which is the version Blender 2.78 and 2.79 officially comes with.
Not sure how to do that exactly but you should try to update to Python 3.5 somehow.

Hope it helps.

I'll try to insert an extra check for this type of error before the release.

**Comment by SVANy** [comment] 2017-07-13 09:11
Thank you for the hint to upgrade my old python version.
Because I'm not really familiar with Linux systems depending on upgrading, compiling etc. I've asked my "personal admin" to do this. But it seems there are problems with updating python, so I fear it will take some time to solve this problem.
Whenever python will be updated successfully, I'll be back again here to report.

So long.

**Comment by JacquesLucke** [comment] 2017-07-13 09:52
ok, make sure you really use python 3.5. The newest version is Python 3.6, but this is not what you need right now. Maybe it is possible that you download a Blender build that ships with it's own Python version.
This is how it works on Windows by default.

**Comment by jasperges** [comment] 2017-07-13 14:15
@SVANy 
If you downloaded blender from blender.org (as you said) python is also included and is version 3.5. The Python version you refer to is probably the system python version, but that is not used by Blender.
If you launch terminal/konsole and type:
```bash
/………./blender-2.78c-linux-glibc219-x86_64/blender
```
(and of course replace the ........ with the actual path) then activate Animtion Nodes again in Blender, you can see the full error message in the terminal. If you can paste it here we can have a look at what is wrong.

**Comment by JacquesLucke** [comment] 2017-07-13 14:57
@jasperges I updated the setup.py file. 
It creates a new `compilation_info.json` file and copies it over to the addon folder (and exports it). This will be read by the `__init__.py` file on startup to check wether the Python version match or not. It won't fix the problem but it will make it easier to find out what the actual problem is.
You can update your test builds on graphicall again to enable this "feature".

Also there is a new command line argument for the `setup.py` file called `--noversioncheck`. Usually when you try to compile AN, it will force you to use Python 3.5.x because this is the officially supported version. You can disable the constraint with the new argument to compile with any Python version you want. Just in case you need that at some point. (But please don't upload them to graphicall yet, it would only create more confusion..)

https://github.com/JacquesLucke/animation_nodes/commit/cc84018077404852172f59ed5749dc82a93ca62b

**Comment by SVANy** [comment] 2017-07-13 15:04
Oh, I see, I couldn't find any explanations on blender.org wether python compiler is in my package or not. Now it's clear to me.

And yes, that's a better way to paste the errormessage than to type it all by myself.
So, here it is:

Traceback (most recent call last):
  File "/root/.config/blender/2.78/scripts/addons/animation_nodes/__init__.py", line 87, in <module>
    try: from . import test_compile
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/sylvia/Öffentlich/HDD_2/Blender_2.78c/blender-2.78c-linux-glibc219-x86_64/2.78/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/root/.config/blender/2.78/scripts/addons/animation_nodes/__init__.py", line 106, in <module>
    raise Exception(message)
Exception: 

This build does not work at the moment.
  1. Make sure that you are using compiled version of AN.
     (Not a direct download of the repository from Github)
  2. Check if the build you downloaded has been compiled for the OS
     you are using. If not, download another one.
  3. If you are on windows you can try to install a library called
     'Visual C++ 2015 Redistributable'. Should be easy to find using
     your search engine of choice.
  4. It is possible that you have a build for the correct platform
     but it still does not work. We experienced this mainly on linux.
     Try to find another build for your platform.
     If it still does not work, you have to compile AN yourself.
  5. Make a bug report on Github and give as much information
     as you can. Specifically the full error message, your OS, version, ...


Blender quit

**Comment by SVANy** [comment] 2017-07-13 15:15
@JacquesLucke 
Indeed I'm a little bit confused now. I don't understand what you've told to jasperges.
Do I have to update python version on my system or not or does blender has its own python compiler in its package?

**Comment by JacquesLucke** [comment] 2017-07-13 15:21
You should try to get Blender to use Python 3.5.
Blender usually has it's own Python "compiler" (it compiles to byte-code and not to machine code). Looks like this is not always the case on Linux.

I've just told @jasperges that he can update the builds on graphicall.
Maybe he can also compile you a build fort testing using Python 3.4 but not sure if that will work.

**Comment by jasperges** [comment] 2017-07-13 16:36
@JacquesLucke Tomorrow I will update the builds on graphicall. Hopefully this will help with future problems.

@SVANy Tomorrow I can also look more into your problem. In the mean time can you open Blender and switch to the Python Console. Then type:
```python
bpy.app.binary_path_python
```
This should report something ending with `python3.5m`. If not can you paste the output here?

Just to double check can you also type:
```python
import sys
sys.version
```
This should report 3.5.x (and some more info). If not can you also paste that output here?

**Comment by SVANy** [comment] 2017-07-13 17:32
@jasperges 

First: it's ending with "..... python3.5m"
Second: it reports "3.5.2 ....."

So no need to copy and paste.

That seems to me that Blender works with his own python and I don't need to install anything new?
So I'll try to be patient and wait for your messages.

Thanks for your help.

**Comment by JacquesLucke** [comment] 2017-07-13 17:53
Hmm unfortunately this does not explain anything.
Could you try this build and send the error message if there is one please?

[animation_nodes.zip](https://github.com/JacquesLucke/animation_nodes/files/1146136/animation_nodes.zip)

**Comment by SVANy** [comment] 2017-07-13 20:29
Unfortunately again an errormessage:

found bundled python: /home/sylvia/Öffentlich/HDD_2/Blender_2.78c/blender-2.78c-linux-glibc219-x86_64/2.78/python
addon_utils.disable: animation_nodes not disabled.
Modules Installed from '/home/sylvia/Öffentlich/HDD_2/Volume/Blender_addons/AnimationNodes_new_1/animation_nodes.zip' into '/root/.config/blender/2.78/scripts/addons' (animation_nodes)
Traceback (most recent call last):
  File "/root/.config/blender/2.78/scripts/addons/animation_nodes/__init__.py", line 130, in <module>
    try: from . import test_compile
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/sylvia/Öffentlich/HDD_2/Blender_2.78c/blender-2.78c-linux-glibc219-x86_64/2.78/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/root/.config/blender/2.78/scripts/addons/animation_nodes/__init__.py", line 147, in <module>
    raise Exception(message)
Exception: 

This build does not work at the moment.
  1. Check if the build you downloaded has been compiled for the OS
     you are using. If not, download another one.
  2. If you are on windows you can try to install a library called
     'Visual C++ 2015 Redistributable'. Should be easy to find using
     your search engine of choice.
  3. It is possible that you have a build for the correct platform
     but it still does not work. We experienced this mainly on linux.
     Try to find another build for your platform.
     If it still does not work, you have to compile AN yourself.
  4. Make a bug report on Github and give as much information
     as you can. Specifically the full error message, your OS, version, ...


Blender quit    




After this procedure I started blender again to remove the addon and then quit blender again.
Now I got the following message from the console:

found bundled python: /home/sylvia/Öffentlich/HDD_2/Blender_2.78c/blender-2.78c-linux-glibc219-x86_64/2.78/python
addon_utils.disable: animation_nodes not disabled.                                                             
Error: Not freed memory blocks: 2, total unfreed memory 0.000732 MB                                            
                                                                                                               
Blender quit           



Thanks for you're working for me so late in the evening.

**Comment by jasperges** [comment] 2017-07-14 06:53
@SVANy This isn't related to your problem, but it seems weird to me that Animation Nodes is installed in `/root/.config/blender/2.78/scripts/addons/`. Normally in your case this should be `/home/sylvia/.config/blender/2.78/scripts/addons/`. How did you install Animation Nodes? If you did it from within Blender, did you run Blender as root?

@JacquesLucke As you can see from the traceback of SVANy Animation Nodes (at least the cython version) needs `libpython3.5m.so.*`. After a quick investigation it seems that this library file is not included in the official builds of Blender for Linux and MacOS. For Windows there *is* `python35.dll` (which I guess is the Windows equivalent) included. So I think that the cython version of Animation Nodes doesn't work on Linux and MacOS if you don't have installed Python3.5 on your system. I have no idea if this lib is not included on purpose or if it's a mistake. Hope this helps...

**Comment by JacquesLucke** [comment] 2017-07-14 08:25
Hm ok, not sure about this either.

What wonders me is that numpy works without problems. 
Cython does nothing too special, it just translates `.pyx` files into a `.c` file (this file uses the CPython C API but is independent from Cython).
Next a standard C compiler takes this file and creates a Python extension module from it. So Animation Nodes should work everywhere where extension modules work. And as numpy works (otherwise we should get another error in the traceback) this obviously is the case.

Maybe I just need to restructure the `setup.py` file again to make the separation from both compilation steps more clear. Then we can figure out how numpy is compiled and see if this helps to make the same AN version work on every Linux (with Python 3.5).

I won't do this before the release though. Will do that a bit later.

**Comment by jasperges** [comment] 2017-07-14 08:50
Just to be sure I renamed my system `libpython3.5m.so` and then I get the same error as SVANy and `numpy` still works correctly.

**Comment by SVANy** [comment] 2017-07-14 08:57
@jasperges 
No, I don't run Blender as root.

I had a look into both directories. All my Addons are definitly in 

`/home/sylvia/.config/blender/2.78/scripts/addons/`

Also Animation Nodes.
In the other directory there is nothing.

But I was wondering, that AN was still in the first directory. I had removed it yesterday after I've called Blender from within the console.
So I run Blender as I normally did and removed it there again. So now it's away.

**Comment by JacquesLucke** [comment] 2017-07-14 08:59
can you give me the path of the file you renamed? Just to avoid misunderstandings.

Ok, so we just have to figure out how to compile AN in a way that it does not need this file. Obviously it is possible somehow because numpy does it (numpy also includes a little bit of cython code).
Maybe I should create a smaller addon for testing.

**Comment by jasperges** [comment] 2017-07-14 09:17
@SVANy Okay, that's good. I was just wandering because in the report it said: `"/root/.config/blender/2.78/scripts/addons/animation_nodes/init.py"`. It seems that unless you can install Python 3.5 on your system, you can't use Animation Nodes 2.0. But this should definitely be solved.

@JacquesLucke `/usr/lib64/libpython3.5m.so` and `/usr/lib64/libpython3.5m.so.1.0`. The first is just a link to the second, but I wanted to be sure. On non 64bit systems this will be `/usr/lib/...`.
If I read the Cython documentation correctly, the files get linked against `libpython3.5m.so`. My guess is that it is being linked dynamically and that's why it needs to find it on the file system. But in this case it should be included statically so it's included. it is possible to configure the build: http://docs.cython.org/en/latest/src/reference/compilation.html#configuring-the-c-build
To be honest, this is over my head, so I might be totally wrong. I will see if I can also test/try some things with this.

**Comment by JacquesLucke** [comment] 2017-07-14 09:31
hmm it's a bit weird that AN requires this system python file even though it uses the python Blender comes with...

Yes this should be solved, but I'm not sure if I can do something about it before the release..

**Comment by jasperges** [comment] 2017-07-14 10:30
@SVANy Can you test this build again: http://graphicall.org/1224 I think it will work now!

@JacquesLucke I compiled Python from source (using `install_deps.sh` from Blender), that gives me a static library `libpython3.5m.a`. If I cythonize Animation Nodes with this Python version it works! I also updated my graphicall linux build.

**Comment by JacquesLucke** [comment] 2017-07-14 10:36
Sounds good. Not sure if fully understand what happend now...
(I only know the basics about linking..)

Would be awesome if this works now!

**Comment by jasperges** [comment] 2017-07-14 10:44
I also don't know much about linking. As far as I understand a dynamically linked library (or shared library) is as the name suggests shared. In the compiled application it just 'points' to this library so it needs to be installed on the computer. A statically linked library is included in the application so it doesn't depend any more on the linked library. So when I passed the static library, it got included.

At least that is my understanding.

**Comment by JacquesLucke** [comment] 2017-07-14 10:47
Did the file size increase?
It sounds like statically linking it into every extension module would have to increase the size a lot. (AN currently has about 80 extension modules)

**Comment by SVANy** [comment] 2017-07-14 11:47
@jasperges 
[http://graphicall.org/1224] will lead me to a page, where I can load 1205 and 1207 but not 1224?

**Comment by JacquesLucke** [comment] 2017-07-14 11:58
you have to click ob the larger download button above..

**Comment by SVANy** [comment] 2017-07-14 12:06
hooray, hooray, it's Christmas Day today

Now it's enabled!

Thank you, guys, very very much for your help. I will ever keep you in my heart.

**Comment by JacquesLucke** [comment] 2017-07-14 12:12
Great!!

Now I just have to learn how to reproduce and fix this myself :D

**Comment by jasperges** [comment] 2017-07-14 12:14
@JacquesLucke The zip archive is not much bigger, just 212199 bytes. The fix is very simple, just use a Python that was build with/as a static library... 😸 

@SVANy Nice!

**Comment by JacquesLucke** [comment] 2017-07-14 12:23
ok thanks. So you basically build AN with the Python Blender comes with? You had to install cython for this version as well then, right?

**Comment by jasperges** [comment] 2017-07-14 15:34
Well... First of all this is Linux specific. With the `install_deps.sh` script you can add the option `--build-python`. Then Python 3.5 is built, whatever you have available on your system. This way the library is built statically (of course you can also build python manually and make it a static library). Then you go into the `/opt/lib/python-3.5/bin` dir and do `./pip install cython`. After that you can build Animation Nodes the the python in `/opt/lib/python-3.5` and all should be fine...

**Comment by JacquesLucke** [comment] 2017-07-14 15:41
Alright, thanks again! Finally a breakthrough in that regard :D

There is still one other problem which may or may not be related: https://github.com/JacquesLucke/animation_nodes/issues/649

Unfortunately I don't really know how to test it myself.

**Closed** 2017-07-14 15:42 UTC
Labels: installation

**Comment by jasperges** [comment] 2017-07-14 16:12
Well... First of all this is Linux specific. With the `install_deps.sh` script you can add the option `--build-python`. Then Python 3.5 is built, whatever you have available on your system. This way the library is built statically (of course you can also build python manually and make it a static library). Then you go into the `/opt/lib/python-3.5/bin` dir and do `./pip install cython`. After that you can build Animation Nodes the the python in `/opt/lib/python-3.5` and all should be fine...
