### ISSUE TITLE
Animation Nodes does not enable in Blender 2.8 (latest build March 27)

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1068] opened 2019-03-27 21:26 UTC
Hi Omar,
I have downloaded the latest build of blender 2.8. Then I have installed the AN but while enabling the AN, it gives this error message:

![Screenshot from 2019-03-28 02-48-20](https://user-images.githubusercontent.com/30294746/55113319-cc405d00-5104-11e9-8e8f-205fa68bc06a.png)

**Comment by OmarSquircleArt** [comment] 2019-03-28 05:11
Thanks for the report. Closing because duplicate of #1061.
I started working on the fix, should be fixed by the end of the day.

**Closed by OmarSquircleArt** 2019-03-28 05:11 UTC
